# Use an official lightweight Python image.
FROM python:3.9-slim

# Install git.
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container.
WORKDIR /app

# Clone git
RUN rm -rf * && git clone https://github.com/SiestaCat/python-files-restapi.git .

# Install dependencies.
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port defined in your application (default is 8080).
EXPOSE 8080

# Run the application with uvicorn.
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]